language: rust
rust:
  - stable
  - beta
  - nightly
sudo: required
dist: bionic
#cache: cargo
# Needed for codecov reporting
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
      - libssl-dev
env: RUST_BACKTRACE=full
before_script:
  - cargo install --force cargo-audit
  - cargo install --force cargo-when
  - rustup component add clippy
  - rustup component add rustfmt
script:
  - cargo clippy --all --all-features -- --deny warnings
  - cargo fmt --all -- --check
  - cargo test --tests --examples
  - cargo test --doc
  - cargo test --all-features
  - cargo audit
after_success: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin &&
  cargo tarpaulin --out Xml &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
notifications:
  email:
    on_success: never
